version: '3.3'

services:
  postgres:
    image: postgres:10
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pfa-autodoc-database
      POSTGRES_USER: shut-up-just-push
      POSTGES_PASSWORD: shut-up-just-push
    command: postgres -N 1000
      #volumes:
    # - 'var/data/postgres:/var/lib/postgresql/data'
  pfa-autodoc-spring-boot-app:
    image: pfaautodoc/backend:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"